### ISSUE TITLE
add snap.svg requirement to documentation

### ISSUE THREAD

**Issue by mariansauter** [jodeleeuw/jsPsych#113]
visual-search-circle requires snap.svg

at the moment it is just a comment in the code;
please add it to the documentation (also on docs.jspsych.org), best with a download link

**Comment by jodeleeuw** [comment]
I'll make sure this gets in. Thanks for pointing it out.

If you want to suggest edits to the docs directly, you can modify the content in the /docs folder of the repository. The docs.jspsych.org site is built from the markdown files in the /docs folder.

**Comment by jodeleeuw** [comment]
Added in dev branch. Will be live when 4.1 is pushed.
