### ISSUE TITLE
make docs in code and on web agree on `continue_after_response` or rename it to remove ambiguity

### ISSUE THREAD

**Issue by mshvartsman** [jodeleeuw/jsPsych#129]
With respect to `continue_after_response`, the docs at http://docs.jspsych.org/plugins/jspsych-single-stim/ say `If true, then the trial will end whenever the subject makes a response` and the code at https://github.com/jodeleeuw/jsPsych/blob/dev/plugins/jspsych-single-stim.js says `true = image will keep displaying after response`. 

I can see how one can interpret it both ways depending on whether the thing that continues after the response is the trial or the experiment (in which case the trial *doesn’t* continue and ends). 

One proposal is renaming it to “response_ends_trial” which I think is unambiguous, and keeping the other name as a deprecated synonym (to be removed at some future date).

**Comment by jodeleeuw** [comment]
This is really useful feedback, thank you! Your suggestion to rename it to `response_ends_trial` is great.

**Comment by jodeleeuw** [comment]
Renamed to response_ends_trial on /dev. Will change in v4.2.
