### ISSUE TITLE
erika: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by erikasf** [jodeleeuw/jsPsych#160]
HI,
If you're not opposed to someone that is just starting out but has experience working in research , psych and the medical field that loves front end ux / design I'm all in.<p><br><blockquote>This issue was created by @erikasf via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by jodeleeuw** [comment]
Welcome! Contributions are welcome and very much appreciated. Take a look at the list of [issues](https://github.com/jodeleeuw/jsPsych/issues) and see if there is something you'd like to work on. If you have a different kind of contribution in mind, propose it as a new issue and we can discuss it.

**Comment by erikasf** [comment]
Thanks! I'll take a look at the issues list and will let you know what I can do to help, or at least what I can attempt to do, after a lot of newly invented curse words comeout of my brain !
