### ISSUE TITLE
Simplify and clean up CSS

### ISSUE THREAD

**Issue by jodeleeuw** [jodeleeuw/jsPsych#163]
The CSS file is a mess with lots of redundant stuff. Clean it up, remove redundancies, and edit plugins to use simplified style set.

**Comment by erikasf** [comment]
do you like Sass? I think it would be effective here. its able to be written with variables etc and then it translates into an easily read css file. I"ll do some and let you look at it and see if its what you want.

**Comment by jodeleeuw** [comment]
SASS might be a good solution long term for letting people adjust the style sheet to do things like match institutional colors. At the moment, my main goal is to take redundant styles and remove them.

For example:

https://github.com/jodeleeuw/jsPsych/blob/master/css/jspsych.css#L156-159

and

https://github.com/jodeleeuw/jsPsych/blob/master/css/jspsych.css#L168-172

are identical, so the CSS is really inefficient. On the dev branch, I added a style that covers both these cases:

https://github.com/jodeleeuw/jsPsych/blob/dev/css/jspsych.css#L49-52

But now all of the plugins need to be adjusted to use that style and the style sheet redundancies need to be removed.

**Comment by jodeleeuw** [comment]
Going to close this because it is covered by #244.
