### ISSUE TITLE
Option to force response in survey-likert

### ISSUE THREAD

**Issue by jodeleeuw** [jodeleeuw/jsPsych#169]
In the survey likert plugin, a subject could hit submit without moving the slider. There is no way to verify that a neutral response is not just a non-response. 

One suggestion via the google group:

>1. The sliders are not shown at first, that is, none of the points are selected.
2. The slider appears when a participant clicks a point.
3. When a participant clicks the submit button, the plugin checks whether a participant responds to all questions.
4. If there are any questions which are not responded yet, a mark appears to indicate it (or the font color of the questions changes from black to red).

**Comment by jodeleeuw** [comment]
Something like this would be a better interface than the slider:
http://codepen.io/Buttonpresser/pen/qiuIx

**Comment by jodeleeuw** [comment]
Overhauled the plugin to use radio buttons instead of slider.

**Comment by elisavanderplas** [comment]
Hi Josh, has this been resolved yet?

**Comment by romainligneul** [comment]
Hello, 
If it can be useful to someone, I've "solved" that problem by adding the following lines of code in the likert plugin, just after the "display_element.innerHTML = html" line.

  // logics to only allow submission after all buttons have been clicked
  var response_array = [];
  document.getElementById("jspsych-survey-likert-next").style.visibility = "hidden";
  var radioButtons = document.querySelectorAll('input[type="radio"]');
  radioButtons.forEach(c => { 
    c.addEventListener("click", function() {
        response_array.push(c.name[1])
        var unique = response_array.filter((item, i, ar) => ar.indexOf(item) === i);
        if (unique.length==trial.questions.length){
            document.getElementById("jspsych-survey-likert-next").style.visibility = "visible";
        }
    });        
  });
