### ISSUE TITLE
problem with shuffle when unpack is set to true

### ISSUE THREAD

**Issue by IanEisenberg** [jodeleeuw/jsPsych#210]
Currently randomization.repeat module shuffles the output of unpackArray when it probably should be the reverse. Changing 998-1002 to:

if (unpack) {
        return unpackArray(out);
      } else {
        return shuffle(out);
}

fixes the error.

As of now it returns an error saying "Array.slice" is not a function because it is trying to slice an object (the output of unpackArray)

**Comment by jodeleeuw** [comment]
this is now fixed in 5.0. just needed to remove the redundant shuffle on the return statement.
