### ISSUE TITLE
single-stim and multi-stim-multi-response unnecessarily attempt to preload text

### ISSUE THREAD

**Issue by ahuanguchi** [jodeleeuw/jsPsych#228]
For example, when I try `tests&examples/jspsych-single-stim.html` with a JavaScript console open, I get a 404 error when jsPsych tries to preload the HTML-formatted stimulus for trial 3 (`'<p>:)</p>'`) even though `is_html` is set to `true`: `GET http://localhost:8000/tests%26examples/%3Cp%3E:)%3C/p%3E 404 (File not found)`. This doesn't break the experiment, but it does make an unnecessary network request.

I only tested this quickly, but it looks like this issue can be fixed by changing line 1552 in `jspsych.js` from

```javascript
if (typeof trials[j][param] !== 'undefined') {
```

to

```javascript
if (typeof trials[j][param] !== 'undefined' && trials[j].is_html !== true) {
```

**Comment by jodeleeuw** [comment]
I'm aware of the issue. I'm trying to figure out a general solution that doesn't rely on the `is_html` flag in the jspsych.js file. That works right now with the set of plugins that currently exist, but might not extend well to future development. 

One idea would be to somehow check if the file path is a valid image before trying to load it.

Another would be to modify the [registerPreload](https://github.com/jodeleeuw/jsPsych/blob/v5.0.2/jspsych.js#L1526-L1538) function to allow for more intelligent registrations that are conditionalized at a plugin-specific level.

**Comment by shamrt** [comment]
How about a [regular expression][1] in the `registerPreload` function? While not the most elegant solution, it may do the trick…

[1]: https://gist.github.com/dperini/729294

**Comment by jodeleeuw** [comment]
I added a `conditional_function` parameter to `registerPreload` that can run an arbitrary function on the trial to see if the preload should be attempted. Right now, this is just used to check if is_html is true or false for the plugins that use it, but can generalize to other cases in the future.
