### ISSUE TITLE
show_progress_bar doesn't show anything

### ISSUE THREAD

**Issue by chanansh** [jodeleeuw/jsPsych#230]
Hi,
I added show_progress_bar: true in my init and I don't see any progress bar.
What could be the root cause?
CSS is added.
Hanan

**Comment by jodeleeuw** [comment]
Can you provide more details about the experiment file? I just tested `show_progress_bar: true` and confirmed that it is working in a simple example, so there must be something about the particular experiment that is causing a problem.

**Comment by chanansh** [comment]
Sure, here you go:

[counter_factual_new.zip](https://github.com/jodeleeuw/jsPsych/files/111459/counter_factual_new.zip)

**Comment by jodeleeuw** [comment]
Haven't tried running this yet, but one idea occurred to me. It might be the result of not setting the `display_element` parameter in the init method. If that parameter is not set, then jsPsych defaults to using the `<body>` element as the display element. However, the progress bar is also shown inside the `<body>` element, so the plugins probably end up destroying the progress bar element inadvertently.

**Comment by chanansh** [comment]
solved! thanks. I think it should be noted in the documentation.

*HS*

**Comment by jodeleeuw** [comment]
Yep, I'll fix it so that it behaves better when display_element isn't set.
