### ISSUE TITLE
Update docs or functionality for same_key / different_key in jspsych-same-different plugin

### ISSUE THREAD

**Issue by jyoshimi** [jodeleeuw/jsPsych#236]
Hello,

Based on these docs

http://docs.jspsych.org/plugins/jspsych-same-different/

it seems that same_key could be set to, for example, 'S'.   But at least on my machine this does not work and so this must be used instead:

jsPsych.pluginAPI.convertKeyCharacterToKeyCode('S')

Suggest either allowing a string or clarifying the documentation.  

Thanks!

**Comment by jodeleeuw** [comment]
this is fixed by allowing the same-different plugin to correctly use string representations of keys
