### ISSUE TITLE
added options in likert plugin & abortExperiment

### ISSUE THREAD

**Issue by adrianoesch** [jodeleeuw/jsPsych#249]
hi josh,

wanted to let you know about two modifications that might be valuable to others too:

1. i added the option to set force responses to "true" in the likert plugin: https://github.com/adrianoesch/jsPsych/blob/master/plugins/jspsych-survey-likert.js

2. additionally i added the abort experiment function (instead of endExperiment) so that it cancels keyboard listeners, a bug i encountered. i use this function in the fullscreen change event listener. https://github.com/adrianoesch/jsPsych/blob/master/jspsych_ao.js#L172

cheers.

PS: i noted that the preamble option isn't in the documentation of the likert plugin ;)

**Comment by jodeleeuw** [comment]
thanks! I'll merge these improvements in once I get around to the next release...

**Comment by jodeleeuw** [comment]
I'm sure I'm missing an obvious situation, but what's the benefit of calling `this.finishTrial()` in `abortExperiment`?

**Comment by adrianoesch** [comment]
i’m not completely sure anymore but i think the experiment would be stuck within the trial and if there’s no timeout set, and therefore the end_message wouldn’t be displayed either. i used the end message in this case to make the participants aware of the failure (f.e. leaving fullscreen).

cheers,
adrian

PS: it might make sense to register timeouts in the core somewhere (similar to the key event listeners) so we could control them from anywhere and kill the timeout with a plugin api call, and not just from within the trial function.

and while i’m writing you already, here’s another thing that might improve the library even further. the more an experiment is relying upon up-to-date api’s it might make sense to check for browser compatibility before launching. i do this with a custom function (https://github.com/timgroup-eth/experiment-dereky/blob/master/anna.html#L111 <https://github.com/timgroup-eth/experiment-dereky/blob/master/anna.html#L111>), why not add something similar to the core? also, checking for a minimum screen size could be of great importance to make sure stimuli are displayed properly.

**Comment by jodeleeuw** [comment]
I think those are both great ideas. 

I've been wanting to add feature detection (#19) for a while now. And custom exclusions (#253), too. If you want to contribute, feel free!

**Comment by jodeleeuw** [comment]
I split this issue up (#279, #280, #253) to make it easier to track progress.
