### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by arnohakk** [jodeleeuw/jsPsych#262]
Hey,

it would be cool if there was a feature making it possible to hold the last image on the screen so that it is not disappearing. 

Cheers

**Comment by jodeleeuw** [comment]
That seems like a worthwhile modification.

You can mimic this behavior for now by using the single-stim plugin after the animation plugin

```javascript
var animation = {
  type: 'animation',
  timing_post_trial: 0
  // ... other parameters for this trial ...
}

var last_frame = {
  type: 'single-stim',
  stimulus: 'last-frame.png'
}

timeline.push(animation, last_frame);
```

**Comment by arnohakk** [comment]
That 'timing_post_trial' option helped! Thank you for your quick reply :)
