### ISSUE TITLE
Server Error when using single-stim plugin

### ISSUE THREAD

**Issue by andrewheusser** [jodeleeuw/jsPsych#268]
In the dev console, after pushing an html formatted stimulus to the timeline: 

```
var trial = {
    type: 'single-stim',
    stimulus: '<p>Radio</p>',
    is_html: true,
    timing_response: 1500,
    response_ends_trial: false
}
```
This error is returned:
`p%3E:1 GET http://localhost:22362/%3Cp%3ERadio%3C/p%3E 500 (INTERNAL SERVER ERROR)`

The odd thing is that it doesn't break the code, the stimulus presents just fine..the errors just clog up the console window.  not sure why there is a get request being made...any ideas?

**Comment by jodeleeuw** [comment]
It's the same issue as #228.

It's harmless, but I'm still thinking about the best way to solve it.

**Comment by andrewheusser** [comment]
sounds good @jodeleeuw !
