### ISSUE TITLE
multi-stim-multi-response: pre-loads images when stimuli are not images

### ISSUE THREAD

**Issue by MetaD** [jodeleeuw/jsPsych#269]
https://github.com/jodeleeuw/jsPsych/blob/master/plugins/jspsych-multi-stim-multi-response.js
line 17: `jsPsych.pluginAPI.registerPreload('multi-stim-multi-response', 'stimuli', 'image');`

This line tries to load images even when the stimuli are not images (i.e. when `is_html` is `true`), which generates ERR_FILE_NOT_FOUND.

**Comment by jodeleeuw** [comment]
This is the same issue as #228. Solution in the works...
