### ISSUE TITLE
example jspsych-text.html and plug-in text do not work

### ISSUE THREAD

**Issue by SSchwoebel** [jodeleeuw/jsPsych#274]
Hello,

I'm using Firefox on Ubuntu and I updated to the newest version of jsPsych today. Since after the update, the above mentioned example does not react to pressing a key. I also use the text plug-in in my experiment, which too does not react to keys anymore, and therefor my experiment does not progress to the next item in the time line. Is there a way to fix this?

**Comment by jodeleeuw** [comment]
Great! The change has to do with how key options are specified in version 6. Instead of an empty array indicating that all keys are valid, and empty array will indicate that no keys are valid, as will the enumerated variable `jsPsych.NO_KEYS`. To specify all keys, you will use `jsPsych.ALL_KEYS`.
