### ISSUE TITLE
White in Videos is Gray

### ISSUE THREAD

**Issue by SSchwoebel** [jodeleeuw/jsPsych#291]
Hello,

I'm using videos with a white background in my experiment. This works fine using chrome and firefox under Linux, but firefox on Windows shows about half of the Videos with a gray background. To be more precise, each single white spot is gray. I can't tell if the whole video is grayed out or if this is just an effect on my eyes from the gray background.

I'm not sure what I can do to solve this. Maybe it's a problem not directly related to jsPsych but more to the video playing abilities of my browser. Maybe you can give me a hint in which direction I can investigate? I'm using .mp4 videos, could you maybe recommend anotyher format?

Thanks in advance!

**Comment by jodeleeuw** [comment]
jsPsych uses the <video> element for the video plugin, so I would start with seeing if this problem is generic to other instances of <video>. I have run several experiments with jsPsych and video and haven't encountered this issue, so I'm not sure what the problem could be. I also used mp4 files.

**Comment by jodeleeuw** [comment]
Closing as this is probably not a jsPsych specific issue.
