### ISSUE TITLE
Feature Request: survey-multi-type plugin

### ISSUE THREAD

**Issue by andrewheusser** [jodeleeuw/jsPsych#292]
I'd like to create a demographic form with questions of multiple formats (text, multi-choice, etc).  Is this possible already?  If not, I'd be happy to give it a shot and submit a PR.

**Comment by jodeleeuw** [comment]
It's not possible yet. The goal is to do this with #135. My current thinking is to create some kind of JSON representation of the form, and then have the plugin render that. Obviously this could get complicated in a hurry, but even a solution with limited options would be really useful. I draw some inspiration from the newest version of Google Forms. The forms look great, there aren't a huge range of options, it's easy to figure out. That would be a fine starting point, and then additional complexity could be added in under the hood.

**Comment by andrewheusser** [comment]
that sounds like a reasonable plan to me.  Since we are hoping to get this experiment up and running, I'm just going to link to a google form with an iframe for now

**Comment by jodeleeuw** [comment]
@andrewheusser, there is a new jspsych-form plugin that does this, fyi.
