### ISSUE TITLE
loop_function breaks the experiment

### ISSUE THREAD

**Issue by roten7** [jodeleeuw/jsPsych#296]
In the current build of jsPsych-master build using a loop_function to loop trials throws an error that appears to be partially related to jQuery as well as jsPsych: "Uncaught RangeError: Maximum call stack size exceeded." There is a commented note near the line that appears to be the origin of the bug that says "// TODO: fix this probably..." Is this already an established bug?

A screenshot of my browser's console log is attached.
![console_log](https://cloud.githubusercontent.com/assets/22083175/19243370/6a44cade-8ee5-11e6-8730-ce2056a3d727.png)

**Comment by jodeleeuw** [comment]
Can you post a reproducible example somewhere?

**Comment by roten7** [comment]
With the current build, running any loop_function will cause the error but my PHP file is included below. If you run it, just proceed past the initial text trial and then the error will be thrown. 

```
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<title>Language Experiment</title>

<script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
<script src="jsPsych-master/jspsych.js"></script>
<script src="jsPsych-master/plugins/jspsych-single-audio.js"></script>
<script src="jsPsych-master/plugins/jspsych-text.js"></script>
<link href="jsPsych-master/css/jspsych.css" rel="stylesheet" type="text/css"></link>
<script>
var trialNumber = 0;

  var intro = {
    type: 'text',
    text: 'Test'
  }


var practice_loop = {
    timeline: [audio_test, text_test],
    loop_function: function(){
        if (trialNumber <= 10){
          return true;
        } else {
          return false;
        }
    }
}

var audio_test = {
  type: 'single-audio',
  stimulus: 'jspsych-6.0/tests&examples/sound/hammer.mp3',
  choices: ['x','.'],
  prompt: 'Hi'
}

var text_test = {
  type: 'text',
  text: 'Success',
}


jsPsych.init({
    timeline: [intro, practice_loop]
  });


</script>
</head>
<style>
</style>
<body>
</body>
</html>
```

**Comment by jodeleeuw** [comment]
I think this is throwing an an error because you defined audio_test and text_test after you used them in the timeline of practice_loop. Try moving them before the definition of practice_loop.

**Comment by roten7** [comment]
That did fix the issue. Oddly enough, my full experiment used to function with the practice_loop setup prior to individual trials being defined and I had no issues. When I updated from 5.0 to the newest version, this error showed up so I assumed it was related to the update and not the setup of my experiment.
