### ISSUE TITLE
Allow plugins to store multiple data rows

### ISSUE THREAD

**Issue by wolfgangwalther** [jodeleeuw/jsPsych#304]
Plugins should be able to store multiple data rows. For example the `survey_`-plugins could make very good use of that, as they collect multiple responses.

Having this data spread over multiple rows makes it easier to analyse the csv-data later with various tools, instead of having a JSON-string in a field. Probably allows for better use of #227 as well.

**Comment by jodeleeuw** [comment]
I've gone back and forth about this. The argument against this is that it removes the clear interpretability of the array structure returned by `jsPsych.data.getData()` where each trial gets a single entry into the array. 

Clearly a better model for data storage is something to think about in depth, and this should be part of that discussion.
