### ISSUE TITLE
preloadAudioFiles bug

### ISSUE THREAD

**Issue by rivasd** [jodeleeuw/jsPsych#308]
Hi Josh, I think we found a small bug in the audio preloading code.

It only ever happens when you run try to preload audio files multiple times without reloading the page, so I know this is a rare case. What happens is that jsPsych.pluginAPIpreloadAudioFiles detects that the buffer objects are still present and thus almost instantaneously executes the callback, but still goes through the process of marking them as 'tmp' and sending the AJAX load call. This leads to erratic behavior where the callback function can be executed both from the main body function at line 1865 and from the AJAX callback at line 1850.

https://github.com/jodeleeuw/jsPsych/blob/master/jspsych.js#L1868

I think a small else clause around lines 1868-1869 would prevent AJAX calls when buffers are still present.

Cheers,
Dan

**Comment by jodeleeuw** [comment]
Thanks!

fixed on no-jquery branch
