### ISSUE TITLE
Overflow of .jspsych-display-element can't be scrolled to

### ISSUE THREAD

**Issue by wolfgangwalther** [jodeleeuw/jsPsych#319]
When creating e.g. a very long instruction that needs to be scrolled to be read completely, the flexbox centering algorithm will cause the top part of the content to be hidden. This part can't be reached by scrolling.

Problem and solution are described in detail at [MDN](https://developer.mozilla.org/en/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes#Flex_Item_Considerations).

In short, those lines on the container elements (`.jspsych-display-element` and `.jspsych-content-wrapper`):
```CSS
align-items: center;
justify-content: center;
```
have to be replaced by `margin: auto` on the child elements (`.jspsych-content-wrapper` and `.jspsych-content`).

**Comment by jodeleeuw** [comment]
I think uncommenting this line fixes the problem:
https://github.com/jodeleeuw/jsPsych/blob/master/css/jspsych.css#L31

I have this fixed on my local copy of the repo but I haven't synced some changes yet.
