### ISSUE TITLE
xmlHttp is not defined -> error in jspych-html plugin

### ISSUE THREAD

**Issue by madebyafox** [jodeleeuw/jsPsych#329]
When running code using the jspsych-html plugin (or the version from the examples folder), I find an error in the JS console: 

Uncaught ReferenceError: xmlHttp is not defined
    at XMLHttpRequest.xmlhttp.onreadystatechange 

I suspect spelling error in pspych-html.js ... am creating a branch now.

**Comment by jodeleeuw** [comment]
fixed by #330
