### ISSUE TITLE
printing data to console w/ getLastTrialData

### ISSUE THREAD

**Issue by madebyafox** [jodeleeuw/jsPsych#331]
I am trying to save data to a db after each trial, and am testing this by printing the last trial's data to the console in the on_finish callback.  This seemed to be working fine in 5.0.3... but when I pulled down the most recent repo I am now only getting an empty {} in place of the data... 

Thoughts?

I've read through a few closed issues... but am also unclear on the callback order of .on_finish, .on_trial_finish and write data.     What is the expected behavior?           Thanks!

**Comment by jodeleeuw** [comment]
The jsPsych.data module was overhauled for version 6 (master branch) but I haven't written the documentation yet. 

This should still work:
```javascript
var trial = {
  // ... 
  on_finish: function(data){
    console.log(JSON.stringify(data));
  }
}
```

**Comment by madebyafox** [comment]
Yup! That works. I was not passing data to the function, rather accessing it as global.  

Thank you!
