### ISSUE TITLE
Uncaught TypeError for same-different plugin first stimulus timing -1

### ISSUE THREAD

**Issue by akochari** [jodeleeuw/jsPsych#333]
When using the same-different plugin with version 5.0.3, there seems to be a bug if I set the timing of the first stimulus to -1.

```
  var block1= {
    type: 'same-different',
    timeline: block1_stim,
    is_html: true,
    same_key: [80],
    different_key: [81],
    timing_first_stim: -1,
    timing_gap: 1000, 
    timing_second_stim: 2500,
    timing_post_trial: random_blank,
  }
```

When the experiment opens the first stimulus, it stops responding to any key presses. Here is the error that I receive in the console:

```
jspsych.js:1166 Uncaught TypeError: Cannot read property 'length' of undefined
    at HTMLDocument.listener_function (jspsych.js:1166)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)

```

**Comment by jodeleeuw** [comment]
Thanks. There was a bug in the code due to an update to the getKeyboardResponse method. It's fixed on the master branch now.
