### ISSUE TITLE
conditional_function never executed for first task

### ISSUE THREAD

**Issue by wilberth** [jodeleeuw/jsPsych#337]
In the following code task1 is shown, which is undocumented behaviour.
~~~~
  var task0 = {
    type: "text",
    text: '<p>task0</p>',
  }

  var task1 = {
    type: "text",
    text: '<p>task1: should not show</p>',
  }

  var task1_container = {
    timeline: [task1],
    conditional_function: function(){ console.log('hello'); return false },
  }

  jsPsych.init({
    timeline: [task1_container] // unexpected: task1 shows
    //timeline: [task0, task1_container] // as intended, task1 does not show
  })
~~~~

**Comment by jodeleeuw** [comment]
Is this version 5? I believe this issue is fixed on the master branch.

**Comment by wilberth** [comment]
It is version 5.0.3

**Comment by jodeleeuw** [comment]
This is fixed for the upcoming version 6. (https://github.com/jodeleeuw/jsPsych/issues/239).

If you need something like this working with version 5, you can add a totally blank trial before the first. For example:

var blank_trial = {
  type: 'single-stim',
  stimulus: '',
  is_html: true,
  timing_response: 1,
}

**Comment by wilberth** [comment]
thanks, sorry for not checking with the latest
