### ISSUE TITLE
jspsych-audio sometimes won't play stimuli

### ISSUE THREAD

**Issue by jtg567** [jodeleeuw/jsPsych#345]
Ordinarily this code works fine: https://github.com/mozilla/braingames/blob/master/games/shrub/game.js#L128, but I found myself in a state today where the audio stimulus was reliably not playing and left the trial hanging until a key was pressed instead of advancing after the audio has completed.

The code worked again after rebooting my system. Running Firefox 51.0.1 on Windows 10; please let me know any other os/hardware information I could provide that would aid in debugging. I'm not sure I could succeed in asking participants to reboot before starting in what I consider the unlikely case this is a pervasive problem.

**Comment by jodeleeuw** [comment]
Is this still a problem, or did it get resolved?

**Comment by jtg567** [comment]
I can't fully disambiguate whether it's not just a problem idiosyncratic to my system, may not be worth investigating further.
