### ISSUE TITLE
localSave() doesn't work anymore

### ISSUE THREAD

**Issue by stopcontrol** [jodeleeuw/jsPsych#347]
The function localSave doesn't work (in Chrome, OsX).

jsPsych.data.localSave('filename', 'csv') returns an error:

Uncaught TypeError: jsPsych.data.localSave is not a function
    at Object.on_finish (Demography_RandomID.html:75)
    at finishExperiment (jspsych.js:769)
    at nextTrial (jspsych.js:794)

**Comment by jodeleeuw** [comment]
If you are using the master branch, some of the documentation is not done yet. http://docs.jspsych.org contains docs for the latest release (v5.0.3).

In v6, localSave works like this:

```js
jsPsych.data.get().localSave('csv', 'myfile.csv');
jsPsych.data.get().localSave('json', 'myfile.json');
```

This allows you to use all of the new data collection methods prior to saving, e.g.:

```js
jsPsych.data.get().filter({trial_type: 'single-stim'}).localSave('csv','single-stim-only.csv');
```

**Comment by stopcontrol** [comment]
Oh, that makes sense! Thanks a lot !!
