### ISSUE TITLE
Feature Request: Custom fullscreen message

### ISSUE THREAD

**Issue by ericawright** [jodeleeuw/jsPsych#368]
Would be great to allow custom string messages to be displayed to the user before they click the `launch experiment` button

```
jsPsych.init({
  timeline: timeline,
  fullscreen: `<p><b>Thank you for participating!</b><br/>This web page will take you through a guided experiment. ETC...<p>`,
 ...
});

**Comment by jodeleeuw** [comment]
I agree. 

If the message and button are customizable, then maybe it makes sense to move this into a plugin to avoid cluttering up the jsPsych.init options in a way that is not consistent with the other kinds of options.

**Comment by jodeleeuw** [comment]
Implemented in new fullscreen plugin.
