### ISSUE TITLE
allow data selection by multiple types

### ISSUE THREAD

**Issue by jcpeterson** [jodeleeuw/jsPsych#378]
I used:

  module.getTrialsOfTypes = function(trial_types) {
    var data = module.getData();

    data = flatten(data);

    var trials = [];
    for (var i = 0; i < data.length; i++) {
      if (trial_types.indexOf(data[i].trial_type) >= 0) {
        trials.push(data[i]);
      }
    }

    return trials;
  };

**Comment by jodeleeuw** [comment]
The new filtering methods on the master branch make this unnecessary.

You could get this by running:
```js
var filtered_data = jsPsych.data.get().filter({trial_type: 'single-stim'}, {trial_type: 'single-audio'});
```

**Comment by jcpeterson** [comment]
Great. When is the next release? I couldn't get the master branch to work?

**Comment by jodeleeuw** [comment]
Hopefully this summer. It's a substantial update and lots of documentation needs to be updated, plus [a few remaining issues](https://github.com/jodeleeuw/jsPsych/issues?q=is%3Aopen+is%3Aissue+milestone%3A6.0). The master branch should be working (I am using it for my experiments). What specific problems are you encountering?
