### ISSUE TITLE
jspsych-form is nonfunctional

### ISSUE THREAD

**Issue by fredcallaway** [jodeleeuw/jsPsych#379]
The provided example does not run for me (tried chrome and safari). First error is at the radio button. `TypeError: this.label.startsWith is not a function`. I tried switching `label` to `labels` in jspsych-form.js, and saw javascript as a label.

**Comment by fredcallaway** [comment]
Also the filler text in textboxes (e.g. "Please enter some texts...") doesn't clear when you write into the box.

**Comment by jodeleeuw** [comment]
@GavinQ1 we should work on this briefly in the summer to make sure compatibility is restored.

**Comment by GavinQ1** [comment]
no problem

**Comment by fredcallaway** [comment]
Sorry all. The issue was due to another script (not one I wrote) modifying the Array prototype which makes the `for i in item` behave strangely.
